[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "python3", "gcc", "pkg-config", "libudev-zero"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node node_modules/serve/build/main.js dist -s -p $PORT"
